name: Five Events
on:
  push:
    branches: [main]
  issues:
    types: [opened]
  release:
    types: [published]
  pull_request:
    types: [opened]
  star:
    types: [created]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
